### ISSUE TITLE
DAAS membership eligibility

### ISSUE THREAD

**Issue by ltfschoen** [validitylabs/daa#5]
How does DAAS determine whether someone has a "substantial relationship to Switzerland". According to "Article 11 Members & Membership Requirements" on Page 4 of the DAAS Statute 170907_DAAS Statues.docx, it appears that eligibility to gain membership of the DAAS is only otherwise available to residents of Switzerland.

**Comment by SCBuergel** [comment]
This is outsourced by the DAAS to the whitelisters.
